### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by hominlinx** [moozik/avmoo-spider#1]
你这个放到数据库里面 如何看视频呢？

**Comment by moozik** [comment]
这个只是爬虫而已，不能直接看视频

**Comment by dashenxiwo** [comment]
启动失败，你这个貌似不能下载封面把？

F:\avmoo-spider>python spider_avmo.py -a   && python spider_avmo.py -t   && python spider_avmo.py -g   && pause
鏁版嵁搴撴渶鏂癐D:000k,绾夸笂鏈€鏂癐D:6xyl
鏈鏇存柊鏁伴噺锛?23929
Traceback (most recent call last):
  File "spider_avmo.py", line 829, in <module>
    avmo()
  File "spider_avmo.py", line 132, in __init__
    self.main(self.get_linkid())
  File "spider_avmo.py", line 379, in main
    data = self.movie_page_data(html)
  File "spider_avmo.py", line 731, in movie_page_data
    if len(lentext) != 0 and '鍒嗛挓' in lentext[0]:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

**Comment by moozik** [comment]
你应该是把文件的编码改了吧，自己研究下
这个没下载封面，只记了个路径，随时可以去cdn下，可是要封面有什么用

**Comment by Lee1Thinker** [comment]
请教下，如何搜索某个女优的所有系列视频并下载番号呢？
