### ISSUE TITLE
麻烦发下最新下好的网盘链接

### ISSUE THREAD

**Issue by shellsec** [moozik/avmoo-spider#11]
整个站抓下来，sqlite的大小应该是100mb左右--20170427
整个站抓下来，sqlite的大小应该是不到300mb--20190610

老板，麻烦丢个盘链接最新下载好的，THX，无上感谢

**Comment by moozik** [comment]
https://pan.baidu.com/s/10x5jg5V7_bLSAflANUaKGg
mxqd
数据结构不太一样

**Comment by shellsec** [comment]
谢谢隔壁老王





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "moozik/avmoo-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [moozik/avmoo-spider] 麻烦发下最新下好的网盘链接 (Issue #11)





 
https://pan.baidu.com/s/10x5jg5V7_bLSAflANUaKGg
 mxqd
 数据结构不太一样
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ND-LJQ** [comment]
大佬能否也给我发一份爬好的数据呢,感激不尽🙏

**Comment by ND-LJQ** [comment]
> 整个站抓下来，sqlite的大小应该是100mb左右--20170427 整个站抓下来，sqlite的大小应该是不到300mb--20190610
> 
> 老板，麻烦丢个盘链接最新下载好的，THX，无上感谢

能否给我也发一份呢,感谢🙏
