### ISSUE TITLE
How to use aqd_spider.py

### ISSUE THREAD

**Issue by trinhtiennguyen** [moozik/avmoo-spider#14]
How to use aqd_spider.py
Thanks in advance.

**Comment by moozik** [comment]
这是一个抓取m3u8视频的爬虫，需要在db添加aqd网站的最新地址
最新地址配置到`av_extend` `(rename,'aqd','https://vip.aqdtv511.com')`

1. `http://127.0.0.1:5000/config`  `av_extend` `(rename,'aqd','https://vip.aqdtv511.com')`
2. `python aqd_spirder.py ./config.ini fetch`
3. `python aqd_spirder.py ./config.ini insert`

**Comment by trinhtiennguyen** [comment]
Thanks alot.
But I have got some error. Please fix. Thanks again.
![image](https://user-images.githubusercontent.com/29258413/162277146-6381f2d8-ee86-456e-816f-f613972c3eae.png)

**Comment by moozik** [comment]
修复了
