### ISSUE TITLE
Exception ignored in thread started by: <bound method Avmo.spider_by_stars of <spider_avmo.Avmo object at 0x000001F30B1ADDC0>>

### ISSUE THREAD

**Issue by trinhtiennguyen** [moozik/avmoo-spider#5]
INSERT: 1
JUX-858         2016-04-30  |Mako Oda
Exception ignored in thread started by: <bound method Avmo.spider_by_stars of <spider_avmo.Avmo object at 0x000001F30B1ADDC0>>
Traceback (most recent call last):
  File "D:\avmoo-spider-master\spider_avmo.py", line 199, in spider_by_stars
    self.movie_save(insert_list)
  File "D:\avmoo-spider-master\spider_avmo.py", line 326, in movie_save
    self.CUR.execute(
sqlite3.OperationalError: near "s": syntax error
SQL CACHE[3092956515]
SQL CACHE[4213925803]
127.0.0.1 - - [16/Jan/2022 21:38:09] "GET /actresses HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2022 21:38:09] "GET /static/app.min.js HTTP/1.1" 304 -
127.0.0.1 - - [16/Jan/2022 21:38:09] "GET /static/app.min.css HTTP/1.1" 304 -
127.0.0.1 - - [16/Jan/2022 21:38:09] "GET /static/face.ico HTTP/1.1" 304 -
![Untitled](https://user-images.githubusercontent.com/29258413/149664852-7d6ab126-d5aa-4a19-b031-eb8c7cae37f4.png)

Can you fix this problem. Thanks in advance.

**Comment by moozik** [comment]
fixed

**Comment by trinhtiennguyen** [comment]
> fixed

Thanks so much. It worked.
