### ISSUE TITLE
Craw with the list of star.

### ISSUE THREAD

**Issue by trinhtiennguyen** [moozik/avmoo-spider#6]
I have a list of id star. 
Ex: 
492e72d8cd235e70
1b98fd64d84ea4b0
5965ef7ff3303bbb 
.....
Do you have any idea about craw it with the list? Thanks in advance.
Sorry for my English.

**Comment by moozik** [comment]
可以用textarea输入star

类似
```
492e72d8cd235e70
1b98fd64d84ea4b0
5965ef7ff3303bbb
```

**Comment by trinhtiennguyen** [comment]
I mean I have a list of ID star in a txt file. How can craw all from txt file. Thanks.

**Comment by moozik** [comment]
copy all text into textarea,craw one by one
just add a textarea

**Comment by trinhtiennguyen** [comment]
<div class="input-group" style="margin-top:20px;">
                
				<textarea class="form-control" id="stars_linkid" rows="3" cols="33" ></textarea>
                <span class="input-group-btn">
                    <button class="btn btn-default" onclick='downloadStar(document.querySelector("#stars_linkid").value)'>下载指定演员</button>
                </span>
            </div>
I try to add textarea but it not work. Can you teach me something? I'm not a programer. Thank in advance.

**Comment by moozik** [comment]
try now,is update

**Comment by trinhtiennguyen** [comment]
Thanks so much, it's worked perfectly.
