### ISSUE TITLE
Banned IP when crawl movie list.

### ISSUE THREAD

**Issue by trinhtiennguyen** [moozik/avmoo-spider#7]
I have got some problem.
1. When I crawl over 20 ID movie, or update movie of Star with many page, very easy to banned IP because it scan to fast. Can you made it scan slow down.
2. Can you add funtion for add movie by search (Exp: https://avmoo.sbs/en/search/CHN) Because many movie don't have Star inside.
Thanks in advance.

**Comment by moozik** [comment]
好建议，开发中

**Comment by trinhtiennguyen** [comment]
One more.
It can not crawl some movie page:
https://avmoo.sbs/en/movie/fc7d707cc1d40d3f
https://avmoo.sbs/en/movie/06bdc731b3b73215
...
With the bigger name Star.
Can you check and fix it.
Thanks in advance.
