### ISSUE TITLE
Can not start flask_avmo.py, using lasttest version.

### ISSUE THREAD

**Issue by trinhtiennguyen** [moozik/avmoo-spider#9]
Hi, I just update lasttest version. But it can not start flask_avmo.py.
![image](https://user-images.githubusercontent.com/29258413/153610746-84360108-d093-475d-9e09-5ca6123a8d78.png)
Please fix it. Thank in advance.

**Comment by moozik** [comment]
![image](https://user-images.githubusercontent.com/11994161/153612155-1a0bfe9f-9e05-49a2-be9f-da80bc8aa7df.png)

我这里是正常的，不知道怎么复现

**Comment by trinhtiennguyen** [comment]
I tried with another PC, and same result, it still can not start. Maybe it conflict 443 port.

**Comment by trinhtiennguyen** [comment]
It's worked. After update python to lastest version. Thank you so much.
![image](https://user-images.githubusercontent.com/29258413/153620616-5fa42733-6694-438f-922d-fd1ef2af4d55.png)

**Comment by shellsec** [comment]
./pip.exe install requests
./pip.exe install lxml
./pip.exe install flask
C:\python310\python.exe -m pip install --upgrade pip
C:\python310\python.exe flask_avmo.py
升级到最新就可以了~
